name: CI - Gamer+
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci
      # - run: npm install

      - name: Lint
        run: npm run lint

      - name: Build Next.js
        run: npm run build

      - name: Tests Vitest
        run: npm run test
